services:
  backend:
    build:
      context: ./backend
    container_name: backend 
    ports:
      - "8001:8000"
    networks:
      - appnet

  frontend:
    container_name: frontend
    restart: always
    image: nginx:latest
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/etc/nginx/html/
    ports:
      - "81:80"
    networks:
      - appnet
    depends_on:
      - backend

networks:
  appnet:
    driver: bridge
