services:
  backend:
    build:
      context: ./backend
    container_name: backend 
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - my-network


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"

    networks:
      - my-network
    
    depends_on:
      - backend



networks:
  my-network:
    driver: bridge
